# secret sample
# {
#   "smtp-password": "xxx",
#   "webserver-secret-key": "xxx",
#   "fernet-key": "xxx",
#   "connection": "postgresql+psycopg2://airflow:xxx@xxx/airflow"
# }

apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-secrets
  namespace: airflow
spec:
  backendType: secretsManager
  region: us-west-2
  data:
  - key: secret-manager-secret-name
    name: smtp-password
    property: smtp-password

  - key: secret-manager-secret-name
    name: webserver-secret-key
    property: webserver-secret-key

  - key: secret-manager-secret-name
    name: fernet-key
    property: fernet-key

  - key: secret-manager-secret-name
    name: connection
    property: connection
